# spring-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: spring-app
spec:
  selector:
    app: spring-app
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: ClusterIP