apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
spec:
  replicas: {{ .Values.keycloak.replicas }}
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: {{ .Values.keycloak.image }}
          ports:
            - containerPort: {{ .Values.keycloak.port }}
          env:
            - name: KC_DB
              value: postgres
            - name: KC_DB_URL_HOST
              value: {{ .Values.keycloak.dbHost }}
            - name: KC_DB_USERNAME
              value: {{ .Values.keycloak.dbUser }}
            - name: KC_DB_PASSWORD
              value: {{ .Values.keycloak.dbPassword }}
            - name: KC_DB_DATABASE
              value: {{ .Values.keycloak.dbName }}
            - name: KC_HTTP_PORT
              value: "{{ .Values.keycloak.port }}"
          args:
            - start-dev
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.keycloak.port }}
      targetPort: {{ .Values.keycloak.port }}
  selector:
    app: keycloak